### ISSUE TITLE
What is the Mac App?

### ISSUE THREAD

**Issue by davidgatti** [mattvenn/simple-brushless#1]
Congrats on the project, very cool. 

I have a question, what is the name of the app that you use for the schematic and simulation?

**Comment by mattvenn** [comment]
Check the links at the bottom of the readme!
I wouldn't normally use ltspice for schematic layout (kicad) but it's cool
for simulation.

On 23 April 2016 at 20:18, David Gatti notifications@github.com wrote:

> Congrats on the project, very cool.
> 
> I have a question, what is the name of the app that you use fro the
> schematic and simulation?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/mattvenn/simple-brushless/issues/1

## 

Matthew Venn
web mattvenn.net twitter @matthewvenn https://twitter.com/matthewvenn

**Comment by davidgatti** [comment]
Yes, the simulation part got me interested. Are there other mac apps for electronics worth knowing?

**Comment by mattvenn** [comment]
not that I know of. I've used some online ones,
http://www.partsim.com/simulator is good, but I just couldn't get the
mosfet to work so gave up and used ltspice.
Matt

On 23 April 2016 at 20:50, David Gatti notifications@github.com wrote:

> Yes, the simulation part got me interested. Are there other mac apps for
> electronics worth knowing?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/mattvenn/simple-brushless/issues/1#issuecomment-213804165

## 

Matthew Venn
web mattvenn.net twitter @matthewvenn https://twitter.com/matthewvenn

**Comment by davidgatti** [comment]
Very Interesting. Thank you for sharing :) 

This e-mail is private, please pass it on to trusted people.
